In [ ]:
import numpy as np
import pandas as pd

## Series/Seriler
series lar pandas dakı aynı numpy dakı diziler veya pythondakı lısteler gıbı ama daha esnek bır yapıya sahıp dıctıonary gıbı de kullanabılen bır yapı

In [ ]:
benimSozlugum={"ahmet":50,"mehmet":40,"zeynep":30}

In [ ]:
pd.Series(benimSozlugum)

ahmet     50
mehmet    40
zeynep    30
dtype: int64

In [ ]:
benimYaslarım=[50,40,30]
benimIsmim=["ahmet","mehmet","zeynep"]

In [ ]:
pd.Series(benimYaslarım,benimIsmim)

ahmet     50
mehmet    40
zeynep    30
dtype: int64

In [ ]:
pd.Series(data=benimYaslarım,index=benimIsmim)

ahmet     50
mehmet    40
zeynep    30
dtype: int64

In [ ]:
numpyDizisi=np.array([50,40,30])

In [ ]:
numpyDizisi

array([50, 40, 30])

In [ ]:
pd.Series(numpyDizisi)

0    50
1    40
2    30
dtype: int64

In [ ]:
pd.Series(numpyDizisi,benimIsmim)

ahmet     50
mehmet    40
zeynep    30
dtype: int64

In [ ]:
pd.Series(["Atıl","Atlas","Osman"],[1,2,3])

1     Atıl
2    Atlas
3    Osman
dtype: object

In [ ]:
yarismaSonucu1=pd.Series([10,5,1],["Atil","Atlas","Osman"])

In [ ]:
yarismaSonucu1

Atil     10
Atlas     5
Osman     1
dtype: int64

In [ ]:
yarismaSonucu2=pd.Series([20,10,8],["Atil","Atlas","Osman"])

In [ ]:
yarismaSonucu2

Atil     20
Atlas    10
Osman     8
dtype: int64

In [ ]:
yarismaSonucu2["Atlas"]

np.int64(10)

In [ ]:
sonSonuc=yarismaSonucu1+yarismaSonucu2

In [ ]:
sonSonuc

Atil     30
Atlas    15
Osman     9
dtype: int64

In [ ]:
farkliSeries=pd.Series([20,30,40,50],["a","b","c","d"])

In [ ]:
farkliSeries2=pd.Series([10,5,3,1],["a","c","f","g"])

In [ ]:
farkliSeries

a    20
b    30
c    40
d    50
dtype: int64

In [ ]:
farkliSeries2

a    10
c     5
f     3
g     1
dtype: int64

In [ ]:
farkliSeries+farkliSeries2

a    30.0
b     NaN
c    45.0
d     NaN
f     NaN
g     NaN
dtype: float64

In [ ]:
##toplama ıslemı burada bırbırlerıyle alakalı kesısenlerı alıyor.

DATAFRAME

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data=np.random.randn(4,3)

In [ ]:
data

array([[-1.64231691, -0.65042261,  0.89446028],
       [-1.42372233,  1.17819549,  2.2260035 ],
       [ 1.24567387,  0.30817489,  1.85654015],
       [-0.31025209, -1.680127  , -1.3641645 ]])

In [ ]:
dataFrame=pd.DataFrame(data)

In [ ]:
dataFrame

          0         1         2
0 -1.642317 -0.650423  0.894460
1 -1.423722  1.178195  2.226004
2  1.245674  0.308175  1.856540
3 -0.310252 -1.680127 -1.364164

In [ ]:
yeniDataFrame=pd.DataFrame(data,index=["Atil","Zeynep","Atlas","Mehmet"],columns=["Maas","Yas","Calisma Saati"])

In [ ]:
yeniDataFrame

            Maas       Yas  Calisma Saati
Atil   -1.642317 -0.650423       0.894460
Zeynep -1.423722  1.178195       2.226004
Atlas   1.245674  0.308175       1.856540
Mehmet -0.310252 -1.680127      -1.364164

In [ ]:
yeniDataFrame["Yas"]

Atil     -0.650423
Zeynep    1.178195
Atlas     0.308175
Mehmet   -1.680127
Name: Yas, dtype: float64

In [ ]:
yeniDataFrame["Calisma Saati"]

Atil      0.894460
Zeynep    2.226004
Atlas     1.856540
Mehmet   -1.364164
Name: Calisma Saati, dtype: float64

In [ ]:
yeniDataFrame[["Maas","Yas"]]

            Maas       Yas
Atil   -1.642317 -0.650423
Zeynep -1.423722  1.178195
Atlas   1.245674  0.308175
Mehmet -0.310252 -1.680127

In [ ]:
yeniDataFrame

            Maas       Yas  Calisma Saati
Atil   -1.642317 -0.650423       0.894460
Zeynep -1.423722  1.178195       2.226004
Atlas   1.245674  0.308175       1.856540
Mehmet -0.310252 -1.680127      -1.364164

In [ ]:
yeniDataFrame.loc["Atil"] #locate yerını belırlemek anlamına gelıyor row olarak secmemızı yarıyor

Maas            -1.642317
Yas             -0.650423
Calisma Saati    0.894460
Name: Atil, dtype: float64

In [ ]:
yeniDataFrame.loc["Zeynep"]

Maas            -1.423722
Yas              1.178195
Calisma Saati    2.226004
Name: Zeynep, dtype: float64

In [ ]:
yeniDataFrame.iloc[1]  #ındex olarak belırlememıze yarıyor

Maas            -1.423722
Yas              1.178195
Calisma Saati    2.226004
Name: Zeynep, dtype: float64

In [ ]:
yeniDataFrame["Emeklilik Yasi"]=yeniDataFrame["Yas"]+yeniDataFrame["Yas"]

In [ ]:
yeniDataFrame

            Maas       Yas  Calisma Saati  Emeklilik Yasi
Atil   -1.642317 -0.650423       0.894460       -1.300845
Zeynep -1.423722  1.178195       2.226004        2.356391
Atlas   1.245674  0.308175       1.856540        0.616350
Mehmet -0.310252 -1.680127      -1.364164       -3.360254

In [ ]:
yeniDataFrame.drop("Emeklilik Yasi",axis=1) #drop dusurmek demek burada axis 1 dememızın sebebı sütün siliyoruz axis = 0 x ekseni axis =1 y ekseni

            Maas       Yas  Calisma Saati
Atil   -1.642317 -0.650423       0.894460
Zeynep -1.423722  1.178195       2.226004
Atlas   1.245674  0.308175       1.856540
Mehmet -0.310252 -1.680127      -1.364164

In [ ]:
yeniDataFrame.drop("Mehmet")

            Maas       Yas  Calisma Saati  Emeklilik Yasi
Atil   -1.642317 -0.650423       0.894460       -1.300845
Zeynep -1.423722  1.178195       2.226004        2.356391
Atlas   1.245674  0.308175       1.856540        0.616350

In [ ]:
#otomatık olarak axis =0 gelmekte

In [ ]:
yeniDataFrame

            Maas       Yas  Calisma Saati  Emeklilik Yasi
Atil   -1.642317 -0.650423       0.894460       -1.300845
Zeynep -1.423722  1.178195       2.226004        2.356391
Atlas   1.245674  0.308175       1.856540        0.616350
Mehmet -0.310252 -1.680127      -1.364164       -3.360254

In [ ]:
#sankı sılmemısız gıbı gorunuyor ayrıca belırtmemız gerekıyor dırekt olarak dataframe uzerınde degısıklık yapmak ıstıyorsak

In [ ]:
yeniDataFrame.drop("Emeklilik Yasi",axis=1,inplace=True) #inplace yerınde ıslemı yapmak ıcın gırıyoruz boolean deger alır

In [ ]:
yeniDataFrame

            Maas       Yas  Calisma Saati
Atil   -1.642317 -0.650423       0.894460
Zeynep -1.423722  1.178195       2.226004
Atlas   1.245674  0.308175       1.856540
Mehmet -0.310252 -1.680127      -1.364164

In [ ]:
yeniDataFrame.loc["Atil"]["Maas"]

np.float64(-1.6423169054870734)

In [ ]:
yeniDataFrame.loc["Atlas","Yas"]

np.float64(0.3081748928466496)

In [ ]:
#ayrı ayrı veya bır lıste ıcerısınde de yazabiliriz

In [ ]:
yeniDataFrame

            Maas       Yas  Calisma Saati
Atil   -1.642317 -0.650423       0.894460
Zeynep -1.423722  1.178195       2.226004
Atlas   1.245674  0.308175       1.856540
Mehmet -0.310252 -1.680127      -1.364164

In [ ]:
booleanFrame=yeniDataFrame<0

In [ ]:
booleanFrame

         Maas    Yas  Calisma Saati
Atil     True   True          False
Zeynep   True  False          False
Atlas   False  False          False
Mehmet   True   True           True

In [ ]:
yeniDataFrame[booleanFrame]

            Maas       Yas  Calisma Saati
Atil   -1.642317 -0.650423            NaN
Zeynep -1.423722       NaN            NaN
Atlas        NaN       NaN            NaN
Mehmet -0.310252 -1.680127      -1.364164

In [ ]:
yeniDataFrame[yeniDataFrame<0]

            Maas       Yas  Calisma Saati
Atil   -1.642317 -0.650423            NaN
Zeynep -1.423722       NaN            NaN
Atlas        NaN       NaN            NaN
Mehmet -0.310252 -1.680127      -1.364164

In [ ]:
yeniDataFrame[yeniDataFrame["Yas"]>0]

            Maas       Yas  Calisma Saati
Zeynep -1.423722  1.178195       2.226004
Atlas   1.245674  0.308175       1.856540

In [ ]:
yeniDataFrame.reset_index()

    index      Maas       Yas  Calisma Saati
0    Atil -1.642317 -0.650423       0.894460
1  Zeynep -1.423722  1.178195       2.226004
2   Atlas  1.245674  0.308175       1.856540
3  Mehmet -0.310252 -1.680127      -1.364164

In [ ]:
yeniDataFrame

            Maas       Yas  Calisma Saati
Atil   -1.642317 -0.650423       0.894460
Zeynep -1.423722  1.178195       2.226004
Atlas   1.245674  0.308175       1.856540
Mehmet -0.310252 -1.680127      -1.364164

In [ ]:
#burada yine inplace kullanmamız gerekıyor

In [ ]:
yeniIndeksListesi=["Ati","Zey","Atl","Meh"]

In [ ]:
yeniDataFrame["yeni Indeks"]=yeniIndeksListesi

In [ ]:
yeniDataFrame

            Maas       Yas  Calisma Saati yeni Indeks
Atil   -1.642317 -0.650423       0.894460         Ati
Zeynep -1.423722  1.178195       2.226004         Zey
Atlas   1.245674  0.308175       1.856540         Atl
Mehmet -0.310252 -1.680127      -1.364164         Meh

In [ ]:
yeniDataFrame.set_index("yeni Indeks")

                 Maas       Yas  Calisma Saati
yeni Indeks
Ati         -1.642317 -0.650423       0.894460
Zey         -1.423722  1.178195       2.226004
Atl          1.245674  0.308175       1.856540
Meh         -0.310252 -1.680127      -1.364164

In [ ]:
yeniDataFrame

            Maas       Yas  Calisma Saati yeni Indeks
Atil   -1.642317 -0.650423       0.894460         Ati
Zeynep -1.423722  1.178195       2.226004         Zey
Atlas   1.245674  0.308175       1.856540         Atl
Mehmet -0.310252 -1.680127      -1.364164         Meh

In [ ]:
#inplace yapmamız gerekıyor

In [ ]:
yeniDataFrame.set_index("yeni Indeks",inplace=True)

In [ ]:
yeniDataFrame

                 Maas       Yas  Calisma Saati
yeni Indeks
Ati         -1.642317 -0.650423       0.894460
Zey         -1.423722  1.178195       2.226004
Atl          1.245674  0.308175       1.856540
Meh         -0.310252 -1.680127      -1.364164

In [ ]:
ilkIndeksler=["Simpson","Simpson","Simpson","SouthPark","SouthPark","SouthPark"]

In [ ]:
icIndeksler=["Homer","Bart","Marge","Cartman","Kenny","Kyle"]

In [ ]:
birlesmisIndeks=list(zip(ilkIndeksler,icIndeksler))

In [ ]:
birlesmisIndeks

[('Simpson', 'Homer'),
 ('Simpson', 'Bart'),
 ('Simpson', 'Marge'),
 ('SouthPark', 'Cartman'),
 ('SouthPark', 'Kenny'),
 ('SouthPark', 'Kyle')]

In [ ]:
birlesmisIndeks=pd.MultiIndex.from_tuples(birlesmisIndeks) #multı ındex bırden fazla ındeks yapmak ıstıyorsak eger, tuple listesi olarka donuyor bıze

In [ ]:
birlesmisIndeks

MultiIndex([(  'Simpson',   'Homer'),
            (  'Simpson',    'Bart'),
            (  'Simpson',   'Marge'),
            ('SouthPark', 'Cartman'),
            ('SouthPark',   'Kenny'),
            ('SouthPark',    'Kyle')],
           )

In [ ]:
benimCizgiFilmListem=[[40,"A"],[10,"B"],[30,"C"],[9,"D"],[10,"E"],[11,"F"]]

In [ ]:
cizgiFilmNumpyDizisi=np.array(benimCizgiFilmListem)

In [ ]:
cizgiFilmDataFrame=pd.DataFrame(cizgiFilmNumpyDizisi,index=birlesmisIndeks,columns=["Yas","Meslek"])

In [ ]:
cizgiFilmDataFrame

                  Yas Meslek
Simpson   Homer    40      A
          Bart     10      B
          Marge    30      C
SouthPark Cartman   9      D
          Kenny    10      E
          Kyle     11      F

In [ ]:
cizgiFilmDataFrame.loc["Simpson"]

      Yas Meslek
Homer  40      A
Bart   10      B
Marge  30      C

In [ ]:
cizgiFilmDataFrame.loc["SouthPark"].loc["Kenny"]

Yas       10
Meslek     E
Name: Kenny, dtype: object

In [ ]:
cizgiFilmDataFrame.index.names=["Film Adı","İsim"]

In [ ]:
cizgiFilmDataFrame

                  Yas Meslek
Film Adı  İsim
Simpson   Homer    40      A
          Bart     10      B
          Marge    30      C
SouthPark Cartman   9      D
          Kenny    10      E
          Kyle     11      F

#Operasyonlar

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
havaDurumuDataFrame=pd.DataFrame({"Istanbul":[30,29,np.nan],"Ankara":[20,np.nan,25],"Izmir":[40,39,38]})

In [ ]:
havaDurumuDataFrame.dropna() #nan olan satırları sıler

   Istanbul  Ankara  Izmir
0      30.0    20.0     40

In [ ]:
havaDurumuDataFrame.dropna(axis=1) #nan olan sütünları sıler

   Izmir
0     40
1     39
2     38

In [ ]:
yeniVeri=pd.DataFrame({"Istanbul":[30,29,np.nan],"Ankara":[20,np.nan,25],"Izmir":[40,39,38],"Antalya":[45,np.nan,np.nan]})
yeniDataFrame=pd.DataFrame(yeniVeri)

In [ ]:
yeniDataFrame

   Istanbul  Ankara  Izmir  Antalya
0      30.0    20.0     40     45.0
1      29.0     NaN     39      NaN
2       NaN    25.0     38      NaN

In [ ]:
yeniDataFrame.dropna(axis=1,thresh=2)  #buradakı thresh kac tane nanlı olursa kaldırmak ıstedıgımız degerı gırıyoruz antalyada 2 tane nan var o yuzden 2 dedık tek nan olanlara dokunmadı

   Istanbul  Ankara  Izmir
0      30.0    20.0     40
1      29.0     NaN     39
2       NaN    25.0     38

In [ ]:
yeniDataFrame.fillna(20) #nan olan verılerı doldurmak ıstedıgımız degerı gırıyoruz.

   Istanbul  Ankara  Izmir  Antalya
0      30.0    20.0     40     45.0
1      29.0    20.0     39     20.0
2      20.0    25.0     38     20.0

## Groupby

In [3]:
import numpy as np
import pandas as pd

In [7]:
maasSozlugu={"Departman":["Yazılım","Yazılım","Pazarlama","Pazarlama","Hukuk","Hukuk"],
             "Calisan Ismi":["Ahmet","Mehmet","Atil","Burak","Zeynep","Fatma"],
             "Maas":[100,150,200,300,400,500]
             }

In [8]:
maasDataFrame=pd.DataFrame(maasSozlugu)

In [9]:
maasDataFrame

   Departman Calisan Ismi  Maas
0    Yazılım        Ahmet   100
1    Yazılım       Mehmet   150
2  Pazarlama         Atil   200
3  Pazarlama        Burak   300
4      Hukuk       Zeynep   400
5      Hukuk        Fatma   500

In [15]:
grupObjesi=maasDataFrame.groupby("Departman")

In [16]:
grupObjesi.count()

           Calisan Ismi  Maas
Departman
Hukuk                 2     2
Pazarlama             2     2
Yazılım               2     2

In [19]:
grupObjesi["Maas"].mean()

Departman
Hukuk        450.0
Pazarlama    250.0
Yazılım      125.0
Name: Maas, dtype: float64

In [21]:
grupObjesi.min()

          Calisan Ismi  Maas
Departman
Hukuk            Fatma   400
Pazarlama         Atil   200
Yazılım          Ahmet   100

In [22]:
grupObjesi.describe()

           Maas
          count   mean        std    min    25%    50%    75%    max
Departman
Hukuk       2.0  450.0  70.710678  400.0  425.0  450.0  475.0  500.0
Pazarlama   2.0  250.0  70.710678  200.0  225.0  250.0  275.0  300.0
Yazılım     2.0  125.0  35.355339  100.0  112.5  125.0  137.5  150.0

pandasla ayrı olan dataları bırlestırme ıslemı
1- aynı sutunlara sahıp ama farklı ıkı verıyı yanı sutun baslıkları aynı ıkısınde de ısımler ve sporlar olsun onu bırlestırmeyı gordum

In [28]:
sozluk1={"Isim":["Ahmet","Mehmet","Zeynep","Atil"],
         "Spor":["Koşu","Yüzme","Koşu","Basketbol"],
         "Kalori":[100,200,300,400]
         }

In [29]:
dataFrame1=pd.DataFrame(sozluk1,index=[0,1,2,3])

In [30]:
dataFrame1

     Isim       Spor  Kalori
0   Ahmet       Koşu     100
1  Mehmet      Yüzme     200
2  Zeynep       Koşu     300
3    Atil  Basketbol     400

In [31]:
sozluk2={"Isim":["Osman","Levent","Atlas","Fatma"],
         "Spor":["Koşu","Yüzme","Badmintoon","Tenis"],
         "Kalori":[200,100,50,300]
         }

In [32]:
dataFrame2=pd.DataFrame(sozluk2,index=[4,5,6,7])

In [33]:
dataFrame2

     Isim        Spor  Kalori
4   Osman        Koşu     200
5  Levent       Yüzme     100
6   Atlas  Badmintoon      50
7   Fatma       Tenis     300

In [35]:
sozluk3={"Isim":["Ayse","Mahmut","Duygu","Nur"],
         "Spor":["Koşu","Yüzme","Badmintoon","Tenis"],
         "Kalori":[300,600,500,200]
         }

In [36]:
dataFrame3=pd.DataFrame(sozluk3,index=[8,9,10,11])

In [37]:
dataFrame3

      Isim        Spor  Kalori
8     Ayse        Koşu     300
9   Mahmut       Yüzme     600
10   Duygu  Badmintoon     500
11     Nur       Tenis     200

In [38]:
#concatenation  alt alt bırlestırme kolonlar aynı ise kullanılıyorsa

In [42]:
pd.concat([dataFrame1,dataFrame2,dataFrame3],axis=0) #pd.concat([dataFrame1,dataFrame2,dataFrame3],axis=1) dersek egerkı yanyana bırlestırır axis yazmassak otomatık olarak axis=0 alır

      Isim        Spor  Kalori
0    Ahmet        Koşu     100
1   Mehmet       Yüzme     200
2   Zeynep        Koşu     300
3     Atil   Basketbol     400
4    Osman        Koşu     200
5   Levent       Yüzme     100
6    Atlas  Badmintoon      50
7    Fatma       Tenis     300
8     Ayse        Koşu     300
9   Mahmut       Yüzme     600
10   Duygu  Badmintoon     500
11     Nur       Tenis     200

##merge iki farklı datayı yan yana bırlestırır ama bır sutunu secerız ve onu anahtar belırlerız bu sayede anahtar belırledıgımız degere gore esleme yapar ve bırlestırır

In [43]:
mergeSozluk1={"isim":["Ahmet","Mehmet","Zeynep","Atıl"], "Spor":["Koşu","Yüzme","Koşu","Basketbol"]}

In [44]:
mergeDataFrame1=pd.DataFrame(mergeSozluk1)

In [45]:
mergeDataFrame1

     isim       Spor
0   Ahmet       Koşu
1  Mehmet      Yüzme
2  Zeynep       Koşu
3    Atıl  Basketbol

In [50]:
mergeSozluk2={"isim":["Ahmet","Mehmet","Zeynep","Atıl"], "Kalori":[100,200,300,400]}
mergeDataFrame2=pd.DataFrame(mergeSozluk2)

In [51]:
mergeDataFrame2

     isim  Kalori
0   Ahmet     100
1  Mehmet     200
2  Zeynep     300
3    Atıl     400

In [52]:
pd.merge(mergeDataFrame1,mergeDataFrame2,on="isim")
#on parametresı ıle anahtarı belırledım eslemem gereken degerı eslesenlerı bırlestırecek

     isim       Spor  Kalori
0   Ahmet       Koşu     100
1  Mehmet      Yüzme     200
2  Zeynep       Koşu     300
3    Atıl  Basketbol     400

pandas ileri seviye metodlar

In [54]:
maasSozluk={"Isim":["Atıl","Zeynep","Mehmet","Ahmet"],
            "Departman":["Yazılım","Satış","Pazarlama","Yazılım"],
            "Maas":[200,300,400,600]}

In [55]:
maasDataFrame=pd.DataFrame(maasSozluk)

In [56]:
maasDataFrame

     Isim  Departman  Maas
0    Atıl    Yazılım   200
1  Zeynep      Satış   300
2  Mehmet  Pazarlama   400
3   Ahmet    Yazılım   600

In [62]:
maasDataFrame["Departman"].unique() #essız degerler yanı tekrarlanan degerlerı getırmıyor

array(['Yazılım', 'Satış', 'Pazarlama'], dtype=object)

In [66]:
maasDataFrame["Departman"].unique() #unıque degerlerın kac tane oldugunu soyler bıze

array(['Yazılım', 'Satış', 'Pazarlama'], dtype=object)

In [69]:
maasDataFrame["Departman"].value_counts() #departmanlarda kacar tane ınsan oldugunu soyleyebılıyoruz yanı aslında sutunu soyleyıp tekrar eden degerlerı sayıyor

Departman
Yazılım      2
Satış        1
Pazarlama    1
Name: count, dtype: int64

In [71]:
#maasları 3 e bolup 5 le carpmak ıstıyorsak eger
def BuruttenNete(maasDegeri):
  return maasDegeri*0.66

In [73]:
maasDataFrame["Maas"].apply(BuruttenNete)  #apply ıle fonksıyonları dataframe uzerınde uygulamamıza yarıyor yanı aslında her deger ıcın tek tek fonksıyonu calıstırmamıza yarıyor

0    132.0
1    198.0
2    264.0
3    396.0
Name: Maas, dtype: float64

burada apply yerıne .map() işlemini de kullanabılırdık, dataframeden bır sutun sectıgım vakıt o aslında serıes olur dataframeler serıeslerden olustugu ıcın ızın verır bıze kullanmamız ıcın cunku map calısabılmesı ıcın serıes olması gerekıyor turun

maasDataFrame["Maas"].map(BuruttenNete)

In [74]:
maasDataFrame.isnull() #null deger var mı yok mu bakar varsa eger true dondurur

    Isim  Departman   Maas
0  False      False  False
1  False      False  False
2  False      False  False
3  False      False  False

In [75]:
#pivot table kullanımı

In [76]:
yeniBirVeri={"Karakter":["SouthPark","SouthPark","Simpson","Simpson"],
             "KarakterIsmi":["Cartman","Kenny","Homer","Bart"],
             "Karakter Yas":[9,10,50,20]}

In [77]:
karakterDF=pd.DataFrame(yeniBirVeri)

In [78]:
karakterDF

    Karakter KarakterIsmi  Karakter Yas
0  SouthPark      Cartman             9
1  SouthPark        Kenny            10
2    Simpson        Homer            50
3    Simpson         Bart            20

In [79]:
karakterDF.pivot_table(values="Karakter Yas",index=["Karakter","KarakterIsmi"])

                        Karakter Yas
Karakter  KarakterIsmi
Simpson   Bart                  20.0
          Homer                 50.0
SouthPark Cartman                9.0
          Kenny                 10.0

In [80]:
#pivot table ın ozellıgı multı ındex yapması aynı zamanda tekrar edenlerı belırleyıp toplatabılıyoruz veya ortalamasını aldırabılıyoruz

In [81]:
yeniBirVeri={"Karakter":["SouthPark","SouthPark","Simpson","Simpson","Simpson"],
             "KarakterIsmi":["Cartman","Kenny","Homer","Bart","Bart"],
             "Karakter Yas":[9,10,50,20,20]}  #yenı aynı deger ekledım yukarıdakıne gore

In [82]:
karakterDF=pd.DataFrame(yeniBirVeri)

In [84]:
karakterDF.pivot_table(values="Karakter Yas",index=["Karakter","KarakterIsmi"],aggfunc=np.sum)

/tmp/ipykernel_1882/2577607326.py:1: FutureWarning: The provided callable <function sum at 0x7ebb5654eb60> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  karakterDF.pivot_table(values="Karakter Yas",index=["Karakter","KarakterIsmi"],aggfunc=np.sum)

                        Karakter Yas
Karakter  KarakterIsmi
Simpson   Bart                    40
          Homer                   50
SouthPark Cartman                  9
          Kenny                   10

In [85]:
#yukarıda mesela bart ısmınde ıkı kısı vardı yazlarını topladı

#Pandas'ta excel ile çalışmak

In [86]:
import pandas as pd

In [89]:
dataFrame=pd.read_excel("calisma.xlsx")

In [91]:
dataFrame

  Unnamed: 0  Maas  Unnamed: 2   Yas  Departman
0       Atıl   100         NaN  40.0    Yazılım
1     Zeynep   150         NaN  50.0      Satış
2     Mehmet   200         NaN  30.0        NaN
3      Ahmet    50         NaN  10.0  Pazarlama
4      Atlas   150         NaN   NaN     Finans
5      Fatma   200         NaN  25.0      Hukuk

In [94]:
df=dataFrame.drop("Unnamed: 2",axis=1)

In [95]:
df

  Unnamed: 0  Maas   Yas  Departman
0       Atıl   100  40.0    Yazılım
1     Zeynep   150  50.0      Satış
2     Mehmet   200  30.0        NaN
3      Ahmet    50  10.0  Pazarlama
4      Atlas   150   NaN     Finans
5      Fatma   200  25.0      Hukuk

In [97]:
doluDegerlerDataFrame=df.dropna(axis=0)

In [98]:
doluDegerlerDataFrame

  Unnamed: 0  Maas   Yas  Departman
0       Atıl   100  40.0    Yazılım
1     Zeynep   150  50.0      Satış
3      Ahmet    50  10.0  Pazarlama
5      Fatma   200  25.0      Hukuk

In [99]:
doluDegerlerDataFrame.to_excel("yenimaas.xlsx")

In [100]:
## read_csv to_csv  excel yerıne dırekt csv derız